################################################################################
#
# crun
#
################################################################################

CRUN_VERSION = 1.7
#CRUN_SITE = $(call github,containers,crun,$(CRUN_VERSION))
CRUN_SITE = https://github.com/containers/crun.git
CRUN_SITE_METHOD = git

CRUN_LICENSE = GPL-2.0+
CRUN_LICENSE_FILES = COPYING

CRUN_DEPENDENCIES = libcap libseccomp libyajl
CRUN_GIT_SUBMODULES = YES

# CRUN_CONF_OPTS = --disable-bpf

define CRUN_RUN_AUTOGEN
	cd $(@D) && \
	echo -e "/* autogenerated.  */\n#ifndef GIT_VERSION\n# define GIT_VERSION \"$(CRUN_GIT_VERSION)\"\n#endif\n" > git-version.h && \
	PATH=$(BR_PATH) ./autogen.sh
endef
CRUN_PRE_CONFIGURE_HOOKS += CRUN_RUN_AUTOGEN


$(eval $(autotools-package))
