#!/bin/bash

function try_mount()
{
	max=3
	try=0
	ret=1
	while [ $try -le $max ]
	do
		mount $1
		[ $? -eq 0 ] && break;
		sleep 1
		echo -ne "try $((++try))/$max $ret\r"
	done
}

function wait_for_dev()
{
	max=5
	try=0
	while [ "${1:0:1}" == "/" ] && [ ! -e $1 ] && [ $((++try)) -le $max ]
	do
		echo -ne "waiting for $1 ($try/$max)\r"
		sleep 1
	done
}

function init_basic_fs()
{
	mount -t proc proc /proc
	mount -t sysfs none /sys
}

echo "====== preinit start"

echo "======-- mount configfs"

# create /media tmpfs and mount configfs there
init_basic_fs
mount -t tmpfs none /media -o size=10M
mkdir /media/configfs

# find configfs device using blkid
CONFIGFS_DEV="$( blkid | awk '/PARTLABEL=\"configfs\"/ {sub(":","",$1); print $1}' )"
mount -t ext4 "$CONFIGFS_DEV" /media/configfs

# mount needed overlays
for dir in etc usr root;
do
	echo "======-- mount overlay for /$dir"
	mkdir -p /media/configfs/$dir
	mkdir -p /media/configfs/workdir/$dir
	mount -t overlay overlay $dir -o lowerdir=/$dir,workdir=/media/configfs/workdir/$dir,upperdir=/media/configfs/$dir
done

read -p "Press any key during next 3s to open a bash interpreter..." -t 3 -n 1 key && bash -i

echo
echo "====== preinit end"

exec /sbin/init

